name: smartui_components
description: "A new smartui components package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.5.0
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  flutter_bloc: ^9.1.1
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  file_picker: ^10.3.6
  image_picker: ^1.2.1
  flutter_svg: ^2.2.2
  url_launcher: ^6.3.2
  geocoding: ^4.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
   assets:
     - assets/images/img_no_available.jpg
