name: Android Play Store Build & Upload

on:
  push:
    branches: [ main ]

jobs:
  build_playstore:
    runs-on: ubuntu-latest

    steps:
      # Checkout project
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Install pub packages
      - name: Install dependencies
        run: flutter pub get

      # Build APK
      - name: Build APK
        run: flutter build apk --release

      # Install Android SDK Build Tools 34 manually
      - name: Install Android Build Tools 34
        run: yes | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"

      # Sign APK
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build/app/outputs/flutter-apk
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          alias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: "34.0.0"

      # Upload to Google Play
      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_JSON }}
          packageName: com.corekit.app
          releaseFile: build/app/outputs/flutter-apk/app-release-signed.apk
          track: internal
