name: Web Dev

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build_web_dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'

      - run: flutter pub get

      - name: Auto Version Upgrade
        run: |
          version_line=$(grep "^version:" pubspec.yaml)
          version_number=$(echo $version_line | cut -d ' ' -f2 | cut -d+ -f1)
          build_number=$(echo $version_line | cut -d+ -f2)
          IFS='.' read -r major minor patch <<< "$version_number"
          patch=$((patch + 1))
          new_version_number="$major.$minor.$patch"
          new_build_number=$((build_number + 1))
          new_version="version: $new_version_number+$new_build_number"
          sed -i "s/^version:.*/$new_version/" pubspec.yaml
          echo "Updated version: $new_version"


      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto Version Bump"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          push_options: --force       # âš¡ Force push to remote
          skip_dirty_check: true      # Skip if nothing changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: flutter analyze || true

      - name: Build Web Dev
        run: flutter build web --release --dart-define=FLAVOR=dev

      - uses: actions/upload-artifact@v4
        with:
          name: web-dev
          path: build/web
